name: "Test"
on:
  pull_request:
  push:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      NIX_PATH: ""
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v3
    - run: nix-build -A buildRustCrateTests
    - run: nix-build -A python36.pkgs.tensorflow
    - run: >
        nix-shell -I nixpkgs=. -E 'with import <nixpkgs> {}; (python3.withPackages (p: [p.tensorflow])).env' --run "python -c 'from tensorflow.contrib import tensor_forest'"
